Qr feature
URLY-WebEngineering/UrlShortener pull request #12
Opened 2020-11-09 16:08 UTC by luisgg98

Now creating a qr code is available on the website and it has been tested using Mocks

2020-11-11 15:15 UTC, jgarciapueyo commented
I have revised the Pull Request. However, because I do not have experience with tests (unit test of controllers and services, or integration tests), I have asked @AlbertoCalvoRubio to finish revising the tests of your PR.

2020-11-11 16:58 UTC, AlbertoCalvoRubio commented on src/main/java/urlshortener/web/QRController.java
> +    this.safeBrowsingService = safeBrowsingService;
I think you don't use this service here

2020-11-11 17:07 UTC, AlbertoCalvoRubio requested changes
- I have written a comment in the code. Please change that
- You should write some test about Service Testing at .. test/java/urlshortener/service , it may take a few lines
- We should wait for Pelicer's feedback about the bug pointed out by SonarCloud

2020-11-12 09:33 UTC, luisgg98 commented
I've corrected what I was doing wrong and removing the unnecessary code or files.
I think it's finally done. Thank you guys for your time and patience.

2020-11-12 09:34 UTC, luisgg98 commented
I've corrected what I was doing wrong and removed the unnecessary code or files.
I think it's finally done. Thank you guys for your time and patience.

2020-11-14 09:44 UTC, AlbertoCalvoRubio approved these changes

2020-11-14 09:46 UTC, AlbertoCalvoRubio commented
Luis try to fix the vulnerability indicated by SonarCloud

2020-11-14 09:55 UTC, luisgg98 commented
According to what the teacher told us I have to make a lots of changes on the code, so I'll start a new PR soon

2020-11-14 09:55 UTC, closed without merging